services:
  - type: web
    name: recipe-parser-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn monitoring.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_monitor_db
          property: connectionString 